### ISSUE TITLE
Delphi compiler availability

### ISSUE THREAD

**Issue by edwinyzh** [Hunter200165/LPatternMatch#1]
Hi,

Thanks for the lib. I was reading the readme and you mentioned you don't have a Delphi compiler. Just in case you didn't know, Delphi now has a real free Community Edition.

**Comment by Hunter200165** [comment]
Hello,

I know about Community Edition and I had it a while ago, but after windows reinstallation it stopped accepting my license key during installation. I may try to reregister just to test it out, but I do not think it worth it.

If you really need to know - I will download it again and test

**Comment by Hunter200165** [comment]
Tested on Delphi compiler, fixed units and updated them in repo
